structures:
  oak-tree: "structure-terrascript-loader:oak_tree_procedural"
  big-oak-tree: "structure-terrascript-loader:oak_tree_procedural"
  birch-tree: "structure-terrascript-loader:birch_tree_procedural"
  acacia-tree: "structure-terrascript-loader:acacia_tree_procedural"
  cherry-tree: "structure-terrascript-loader:cherry_blossom_tree_procedural"
  dark-oak-tree: "structure-terrascript-loader:dark_oak_tree_procedural"
  tall-jungle-tree: "structure-terrascript-loader:large_jungle_tree_procedural"
  small-jungle-tree: "structure-terrascript-loader:medium_jungle_tree_procedural"
  mangrove-tree: "structure-terrascript-loader:mangrove_tree_procedural"
  pale-oak-tree: "structure-terrascript-loader:large_pale_oak_tree_procedural"
  spruce-tree: "structure-terrascript-loader:spruce_tree_procedural"
settings:
  debug: false
  debug-world-name: world