name: TerraTrees
version: '2.0.0'
main: me.rabbittv.terraTrees.TerraTrees
folia-supported: true
description: A plugin to spawn Terra structures instead of vanilla trees
author: RabbitTV
website: https://modrinth.com/plugin/terratrees
api-version: '1.21'
dependencies:
  server:
    Terra:
      load: BEFORE
      required: true